### ISSUE TITLE
[Crop&Soil] Investigate `ManurePool` Division by Zero Error in `barnyard_metadata`

### ISSUE THREAD

**Issue by allisterakun** [RuminantFarmSystems/RuFaS#2024]
When simulating with `barnyard_metadata.json` under the `dev` branch, the following Division by Zero error is thrown that crashes the simulation.
## Expected Behavior

The simulation should run without crashing for all the valid metadata files.
## Current Behavior

A Division by Zero Error is causing the simulation to crash.

> [26-Sep-2024_Thu_16-43-46.683057][ERROR][default] Failed to finish task: 1/1 with output prefix: default. Failed to recover from error: float division by zero; traceback: Traceback (most recent call last):
  File "D:\Work\Cornell\MASM\RUFAS\task_manager.py", line 388, in task
    TaskManager.call_handler(
  File "D:\Work\Cornell\MASM\RUFAS\task_manager.py", line 322, in call_handler
    handler(args, input_manager, output_manager, task_id, produce_graphics)
  File "D:\Work\Cornell\MASM\RUFAS\task_manager.py", line 634, in _handle_simulation_engine_run_tasks
    TaskManager.handle_single_simulation_run(args, output_manager)
  File "D:\Work\Cornell\MASM\RUFAS\task_manager.py", line 445, in handle_single_simulation_run
    simulator.simulate()
  File "D:\Work\Cornell\MASM\RUFAS\simulation_engine.py", line 89, in simulate
    self._run_simulation_main_loop()
  File "D:\Work\Cornell\MASM\RUFAS\simulation_engine.py", line 121, in _run_simulation_main_loop
    self._annual_simulation()
  File "D:\Work\Cornell\MASM\RUFAS\simulation_engine.py", line 171, in _annual_simulation
    self._daily_simulation()
  File "D:\Work\Cornell\MASM\RUFAS\simulation_engine.py", line 135, in _daily_simulation
    self.field_manager.daily_update_routine(self.weather, self.time)
  File "D:\Work\Cornell\MASM\RUFAS\routines\field\manager\field_manager.py", line 89, in daily_update_routine
    field.manage_field(time, current_conditions=current_conditions)
  File "D:\Work\Cornell\MASM\RUFAS\routines\field\field\field.py", line 205, in manage_field
    self._execute_daily_processes(current_conditions, time)
  File "D:\Work\Cornell\MASM\RUFAS\routines\field\field\field.py", line 1230, in _execute_daily_processes
    self._cycle_water(current_conditions, time)
  File "D:\Work\Cornell\MASM\RUFAS\routines\field\field\field.py", line 1297, in _cycle_water
    self.soil.phosphorus_cycling.cycle_phosphorus(
  File "D:\Work\Cornell\MASM\RUFAS\routines\field\soil\phosphorus_cycling\phosphorus_cycling.py", line 71, in cycle_phosphorus
    self.manure.daily_manure_update(rainfall, runoff, field_size, mean_air_temperature)
  File "D:\Work\Cornell\MASM\RUFAS\routines\field\soil\phosphorus_cycling\manure.py", line 62, in daily_manure_update
    machine_total = self.data.machine_manure.daily_manure_update(rainfall, field_size, mean_air_temperature)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Work\Cornell\MASM\RUFAS\routines\field\soil\manure_pool.py", line 107, in daily_manure_update
    self.adjust_manure_moisture_factor(rainfall, temperature_factor)
  File "D:\Work\Cornell\MASM\RUFAS\routines\field\soil\manure_pool.py", line 255, in adjust_manure_moisture_factor
    change_in_machine_manure_moisture = self._determine_moisture_change(
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Work\Cornell\MASM\RUFAS\routines\field\soil\manure_pool.py", line 462, in _determine_moisture_change
    return (-1) * (-0.05 * (current_mass / original_mass) + 0.075) * temperature_factor
                            ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
ZeroDivisionError: float division by zero

[26-Sep-2024_Thu_16-43-46.722561][ERROR][Task Manager] Task(s) failed. Failed task(s) and output prefix are: ['default (1/1)']
Finished task: TASK_MANAGER with 1 error(s), 85 warning(s), and 19 log(s).

Process finished with exit code 0


## Steps to Reproduce
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1. Switch to the `dev` branch.
2. Go to `input/data/tasks/default_task.json`
3. Change the "metadata_file_path" value to "input/metadata/barnyard_metadata.json"
4. Run the simulation.

## Action Items
1. Investigate the reason of crashing.
2. Coordinate with the SMEs about a possible solution.
3. Investigate other metadata files to make sure all they are all working without errors.

**Comment by matthew7838** [comment]
Grooming: Objective is to investigate the root cause of issue and propose a fix which might be 1. Changing validation rules in metadata. 2. Postponing this issue to cross-validation. 3. Adding/modifying the logic to either prevent division by zero or catch it.

**Comment by matthew7838** [comment]
Consolidated with #2027.
