### ISSUE TITLE
[Animal] Lack of genetic data causes simulation to crash if start date is too early

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#2053]
RuFaS crashes in a not so graceful way if the start date is too early.

## Expected Behavior

RuFaS should be able to start and end on any arbitrary dates, assuming that there is enough weather data to support that simulation and the end date is after the start date.

## Current Behavior

If the simulation starts before Tuesday, May 22 of 2012 (day 122), RuFaS crashes with the error:
```
[01-Nov-2024_Fri_15-19-16.525102][ERROR][default] Failed to finish task: 1/1 with output prefix: default. Failed to recover from error: '2006-01'; traceback: Traceback (most recent call last):
  File "/home/isgotkowitz/rufas/RUFAS/task_manager.py", line 406, in task
    TaskManager.call_handler(
  File "/home/isgotkowitz/rufas/RUFAS/task_manager.py", line 340, in call_handler
    handler(args, input_manager, output_manager, task_id, produce_graphics)
  File "/home/isgotkowitz/rufas/RUFAS/task_manager.py", line 665, in _handle_simulation_engine_run_tasks
    TaskManager.handle_single_simulation_run(args, output_manager)
  File "/home/isgotkowitz/rufas/RUFAS/task_manager.py", line 451, in handle_single_simulation_run
    TaskManager.handle_herd_initializaition(args, output_manager)
  File "/home/isgotkowitz/rufas/RUFAS/task_manager.py", line 440, in handle_herd_initializaition
    herd_factory.initialize_herd()
  File "/home/isgotkowitz/rufas/RUFAS/routines/animal/life_cycle/herd_factory.py", line 409, in initialize_herd
    self.pre_animal_population = self._initialize_herd_from_data(time)
  File "/home/isgotkowitz/rufas/RUFAS/routines/animal/life_cycle/herd_factory.py", line 301, in _initialize_herd_from_data
    cows = list(
  File "/home/isgotkowitz/rufas/RUFAS/routines/animal/life_cycle/herd_factory.py", line 256, in _init_animal_from_data
    net_merit=AnimalGenetics.assign_net_merit_value_to_animals_entering_herd(
  File "/home/isgotkowitz/rufas/RUFAS/routines/animal/genetics/animal_genetics.py", line 200, in assign_net_merit_value_to_animals_entering_herd
    average = AnimalGenetics.net_merit[breed][birth_year_month]["average"]
KeyError: '2006-01'

[01-Nov-2024_Fri_15-19-16.551328][ERROR][Task Manager] Task(s) failed. Failed task(s) and output prefix are: ['default (1/1)']
```

## Possible Solution

Use the earliest known data for any dates from before the actual data begins, and log an error telling the user that this happened.

## Steps to Reproduce

1. Set weather data of default simulation to be `swat_weather.json`
2. Set the start date to be "2012:122" (or any date before then)
3. Run the simulation

## Detailed Description

@allisterakun and @YijingGong will be the best people to consult when implementing a solution to this problem.

**Comment by allisterakun** [comment]
@allisterakun will coordinate with @YijingGong to see if it's feasible to use linear projection to estimate genetic data before 2006 (the current starting point).

**Comment by Isgotkowitz** [comment]
This issue is tied to #2068

**Comment by tomhuhh** [comment]
Hi Team! I ran into the following error when working with one of my farms:  'Animal birthdate out of range for animal genetics data. No net merit data for 2005-04, using data from closest available date: 2006-02'. I wonder if it has to do with this issue? Thank you!
