### ISSUE TITLE
Issue Report: Body Weight Calculation Discrepancy in RuFaS Simulation

### ISSUE THREAD

**Issue by tomhuhh** [RuminantFarmSystems/RuFaS#2060]
## Expected Behavior

The average body weight of lactating cows should align closely with / below the targeted mature body weight set during initialization (544 kg).

## Current Behavior

- For a 50-cow herd (Farm C1 in branch 'Aguirre-Villegas-2024'), after initializing with a targeted mature body weight of 544 kg, the RuFaS simulation produced an average lactating cow body weight of 637 kg, significantly higher than expected.
- In scenarios with larger herd sizes (200 and 1000 cows), the simulated lactating cow body weights were lower than the targeted mature body weight.

## Possible Solution

This discrepancy may be due to an issue with the animal database initialization or the scaling of body weight calculations based on herd size. Reviewing the body weight parameter handling and cross-referencing with initialization settings might help pinpoint the cause.

## Steps to Reproduce

1. Initialize a 50-cow herd in Farm C1 with a mature body weight of 544 kg.
2. Run the input files for C1.
3. Compare the resulting average body weight for lactating cows with the targeted value.
4. Repeat with herd sizes of 200 and 1000 for cross-comparison.

## Context (Environment)

This issue occurred in the 'Aguirre-Villegas-2024' branch during simulations of different herd sizes, mostly impacting body weight outcomes in RuFaS model runs for lactating cows.

## Detailed Description

This report pertains to a body weight discrepancy observed during a simulation of a 50-cow herd (Farm C1) in my 'Aguirre-Villegas-2024' branch. Although the herd was initialized with a target mature body weight of 544 kg, the output average body weight for lactating cows was 637 kg. In contrast, two other scenarios with herd sizes of 200 and 1000 cows resulted in lactating cow body weights that were lower than the initial target.

## Possible Implementation

An evaluation of the animal initialization and a detailed check of the scaling mechanism used for different herd sizes could provide insights for a potential fix.

## Target Deadline

Please consult with Kristan or Pooya.

**Comment by KFosterReed** [comment]
I tried running just a herd initialization task on this branch with the C1_metadata inputs and saving the animal population file and got this error: 

[12-Nov-2024_Tue_21-11-39.030701][ERROR][herd_init] Failed to finish task: 1/1 with output prefix: herd_init. Failed to recover from error: [Errno 2] No such file or directory: 'input\\animal\\animal_pop\\animal_population-12-Nov-2024_Tue_21-11-38.json'; traceback: Traceback (most recent call last):
  File "C:\Users\Kristan Reed\RuFaSRepo\MASM\RUFAS\task_manager.py", line 388, in task
    TaskManager.call_handler(
  File "C:\Users\Kristan Reed\RuFaSRepo\MASM\RUFAS\task_manager.py", line 322, in call_handler
    handler(args, input_manager, output_manager, task_id, produce_graphics)
  File "C:\Users\Kristan Reed\RuFaSRepo\MASM\RUFAS\task_manager.py", line 619, in _handle_herd_init_tasks
    TaskManager.handle_herd_initializaition(args, output_manager)
  File "C:\Users\Kristan Reed\RuFaSRepo\MASM\RUFAS\task_manager.py", line 422, in handle_herd_initializaition       
    herd_factory.initialize_herd()
  File "C:\Users\Kristan Reed\RuFaSRepo\MASM\RUFAS\routines\animal\life_cycle\herd_factory.py", line 372, in initialize_herd
    om.dict_to_file_json(
  File "C:\Users\Kristan Reed\RuFaSRepo\MASM\RUFAS\output_manager.py", line 575, in dict_to_file_json
    raise e
  File "C:\Users\Kristan Reed\RuFaSRepo\MASM\RUFAS\output_manager.py", line 559, in dict_to_file_json
    with open(path, "w") as json_file:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'input\\animal\\animal_pop\\animal_population-12-Nov-2024_Tue_21-11-38.json'


Because function to save the animal population file is not working, we can't verify if the herd initialization function is working.

**Comment by tomhuhh** [comment]
I believe this issue has been resolved, with the cause identified as user error. Moving forward, it’s important to remember that whenever the animal database is regenerated, we must update its pathname in the metadata file to ensure the correct file is referenced.

So I am closing the issue...
