### ISSUE TITLE
Simulate single cow

### ISSUE THREAD

**Issue by tlh96** [RuminantFarmSystems/RuFaS#80]
Modify code so a single cow can be represented. Error below.

Simulating: animal_management.json
Traceback (most recent call last):
  File "c:/Users/tlh96/Desktop/MASM-master/main.py", line 45, in <module>
    main()
  File "c:/Users/tlh96/Desktop/MASM-master/main.py", line 38, in main
    RUFAS.simulate(input_file_path)
  File "c:\Users\tlh96\Desktop\MASM-master\RUFAS\simulation_engine.py", line 61, in simulate
    annual_simulation()
  File "c:\Users\tlh96\Desktop\MASM-master\RUFAS\simulation_engine.py", line 112, in annual_simulation
    daily_simulation()
  File "c:\Users\tlh96\Desktop\MASM-master\RUFAS\simulation_engine.py", line 77, in daily_simulation
    routines.daily_animal_routine(state.animal_management, state.feed, weather, time)
  File "c:\Users\tlh96\Desktop\MASM-master\RUFAS\routines\animal\animal_management.py", line 38, in daily_animal_routine
    animal_management.daily_updates(feed, weather, time)
  File "c:\Users\tlh96\Desktop\MASM-master\RUFAS\routines\animal\animal_management.py", line 604, in daily_updates
    self.heiferIIIs, self.cows)
  File "c:\Users\tlh96\Desktop\MASM-master\RUFAS\routines\animal\life_cycle\life_cycle.py", line 471, in daily_update
    removed = heiferIIIs.pop()

**Comment by militsasotirova** [comment]
This issue is fixed in both the sensitivity analysis and life cycle cleanup branches.
